workflows:
  build-android:
    name: Compilation de l'APK Android
    max_build_duration: 20
    environment:
      flutter: stable
      xcode: latest
      vars:
        PACKAGE_NAME: "com.alrc-radio"
    scripts:
      - name: Get Flutter dependences
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk